EmStop1_1:
  - Event ID : 300
  - Memory Position: 2
  - Emergency Stop 1 has been pressed

EmStop1_2:
  - Event ID : 301
  - Memory Position: 2
  - Emergency Stop 1 has been released

EmStop2_1:
  - Event ID : 302
  - Memory Position: 5
  - Emergency Stop 2 has been pressed

EmStop2_2:
  - Event ID : 303
  - Memory Position: 5
  - Emergency Stop 2 has been realesed 

Coupling_IRM_TECNALIA_1:
  - Event ID : 400
  - Memory Position: 6
  - Disacoupling IRM TECANALIA event

Coupling_IRM_TECNALIA_2:
  - Event ID : 4001
  - Memory Position: 6
  - Coupling IRM TECANALIA event